spring.application.name=backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/buildfolio}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# OpenAI API Key
spring.ai.openai.api.key=${OPENAI_API_KEY}

# Chat model
spring.ai.openai.chat.options.model=gpt-4o-mini

# Embedding model
spring.ai.openai.embedding.options.model=text-embedding-3-small


## Flyway
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=truespring.application.name=backend



